# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'res\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(742, 984)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res\\icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setStyleSheet("background-color: blue")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(742, 984))
        self.centralwidget.setMaximumSize(QtCore.QSize(742, 984))
        self.centralwidget.setObjectName("centralwidget")
        self.roll = QtWidgets.QLabel(self.centralwidget)
        self.roll.setGeometry(QtCore.QRect(0, 0, 741, 984))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roll.sizePolicy().hasHeightForWidth())
        self.roll.setSizePolicy(sizePolicy)
        self.roll.setStyleSheet("background-color: rgba(0, 0, 0, 0)")
        self.roll.setText("")
        self.roll.setPixmap(QtGui.QPixmap("res/1.png"))
        self.roll.setScaledContents(True)
        self.roll.setObjectName("roll")
        self.mainText = QtWidgets.QLabel(self.centralwidget)
        self.mainText.setGeometry(QtCore.QRect(90, 90, 571, 761))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(58)
        self.mainText.setFont(font)
        self.mainText.setStyleSheet("background-color: rgba(0, 0, 0, 0)")
        self.mainText.setScaledContents(True)
        self.mainText.setAlignment(QtCore.Qt.AlignCenter)
        self.mainText.setWordWrap(True)
        self.mainText.setObjectName("mainText")
        self.script = QtWidgets.QLabel(self.centralwidget)
        self.script.setGeometry(QtCore.QRect(0, 0, 741, 984))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.script.sizePolicy().hasHeightForWidth())
        self.script.setSizePolicy(sizePolicy)
        self.script.setAutoFillBackground(False)
        self.script.setText("")
        self.script.setPixmap(QtGui.QPixmap("res/2.png"))
        self.script.setScaledContents(True)
        self.script.setObjectName("script")
        self.titleText = QtWidgets.QLabel(self.centralwidget)
        self.titleText.setGeometry(QtCore.QRect(80, 850, 611, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        self.titleText.setFont(font)
        self.titleText.setStyleSheet("background-color: rgba(0, 0, 0, 0)")
        self.titleText.setScaledContents(True)
        self.titleText.setAlignment(QtCore.Qt.AlignCenter)
        self.titleText.setObjectName("titleText")
        self.script.raise_()
        self.roll.raise_()
        self.mainText.raise_()
        self.titleText.raise_()
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "SoG-client"))
        self.mainText.setText(_translate("mainWindow", "1. Так совершены небо и земля и все воинство их."))
        self.titleText.setText(_translate("mainWindow", "Бытие 2"))
